services:
  db:
    image: postgres:18.0
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRES_USER: flowbook
      POSTGRES_PASSWORD: flowbook
      POSTGRES_DB: flowbook

volumes:
  db:
